# Generated by Django 4.2 on 2023-05-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_songs_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortfilter',
            name='description',
            field=models.TextField(default='Sort Filter Desciption'),
        ),
    ]
