# Generated by Django 4.2 on 2023-05-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sortfilter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Raga',
            field=models.CharField(default='Sindhubhairavi', max_length=30),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(max_length=10000, upload_to='Songs'),
        ),
    ]
