# Generated by Django 4.2 on 2023-05-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_song_deity_image_alter_song_audio_file_alter_song_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='deity_image',
            field=models.ImageField(default='default.png', upload_to='deity_images'),
        ),
    ]
