# Generated by Django 4.2 on 2023-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_song_deity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='deity_image',
            field=models.ImageField(default='default.png', upload_to='media/deity_images'),
        ),
    ]
