# Generated by Django 4.2 on 2023-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_song_deity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.png', upload_to='god_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='deity_image',
        ),
    ]
