# Generated by Django 4.2 on 2023-05-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_song_god'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='Raga',
        ),
        migrations.AddField(
            model_name='song',
            name='Raaga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.raaga'),
        ),
    ]
