# Generated by Django 4.2 on 2023-06-02 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_raaga_remove_song_raga_song_raaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
