# Generated by Django 4.1.7 on 2023-08-12 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_song_lyrics_pdf_alter_song_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='favourite',
            field=models.ManyToManyField(default='lyrics/LYRIC_FILE_NOT_YET_UPLOADED.pdf', editable=False, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
