# Generated by Django 4.1.7 on 2023-09-24 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_alter_song_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='favourite',
            field=models.ManyToManyField(editable=False, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics_pdf',
            field=models.FileField(default='media/lyric/LYRIC_FILE_NOT_YET_UPLOADED.pdf', max_length=1000000000, null=True, upload_to='lyrics'),
        ),
    ]
