# Generated by Django 4.1.7 on 2023-09-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_song_favourite_alter_song_lyrics_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics_pdf',
            field=models.FileField(max_length=1000000000, null=True, upload_to='lyrics'),
        ),
    ]
